import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Clipboard from "react-clipboard.js";
import syntaxHighlight from "../utils/syntaxHighlight";
import { useTimedState } from "../hooks/useTimeout";
import { processRecipeLine } from "../utils/ingredientsParsing";
import UNITS from "../utils/units";
import Link from "next/link";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  const [val, setVal] = useState("");
  const [output, setOutput] = useState("");
  const [copiedVisible, setCopiedVisible] = useTimedState(false, 1500);

  return (
    <>
      <Head>
        <title>VegWeek App Ingredient Parser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>VegWeek Parser</h1>
    </>
  );
};

export default Home;
